/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsoleIndexRouteImport } from './routes/_console/index'
import { Route as ConsoleAboutRouteImport } from './routes/_console/about'
import { Route as ConsoleDisputesRouteImport } from './routes/_console/disputes'
import { Route as ConsoleEvaluationRouteImport } from './routes/_console/evaluation'
import { Route as ConsolePoliciesRouteImport } from './routes/_console/policies'
import { Route as ConsoleDisputesIndexRouteImport } from './routes/_console/disputes/index'
import { Route as ConsoleDisputesCaseIdRouteImport } from './routes/_console/disputes/$caseId'

const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAboutRoute = ConsoleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDisputesRoute = ConsoleDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleEvaluationRoute = ConsoleEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsolePoliciesRoute = ConsolePoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDisputesIndexRoute = ConsoleDisputesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleDisputesRoute,
} as any)
const ConsoleDisputesCaseIdRoute = ConsoleDisputesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => ConsoleDisputesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsoleIndexRoute
  '/login': typeof LoginRoute
  '/about': typeof ConsoleAboutRoute
  '/disputes': typeof ConsoleDisputesRouteWithChildren
  '/evaluation': typeof ConsoleEvaluationRoute
  '/policies': typeof ConsolePoliciesRoute
  '/disputes/$caseId': typeof ConsoleDisputesCaseIdRoute
  '/disputes/': typeof ConsoleDisputesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof ConsoleAboutRoute
  '/evaluation': typeof ConsoleEvaluationRoute
  '/policies': typeof ConsolePoliciesRoute
  '/': typeof ConsoleIndexRoute
  '/disputes/$caseId': typeof ConsoleDisputesCaseIdRoute
  '/disputes': typeof ConsoleDisputesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/_console/about': typeof ConsoleAboutRoute
  '/_console/disputes': typeof ConsoleDisputesRouteWithChildren
  '/_console/evaluation': typeof ConsoleEvaluationRoute
  '/_console/policies': typeof ConsolePoliciesRoute
  '/_console/': typeof ConsoleIndexRoute
  '/_console/disputes/$caseId': typeof ConsoleDisputesCaseIdRoute
  '/_console/disputes/': typeof ConsoleDisputesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/disputes'
    | '/evaluation'
    | '/policies'
    | '/disputes/$caseId'
    | '/disputes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/evaluation'
    | '/policies'
    | '/'
    | '/disputes/$caseId'
    | '/disputes'
  id:
    | '__root__'
    | '/_console'
    | '/login'
    | '/_console/about'
    | '/_console/disputes'
    | '/_console/evaluation'
    | '/_console/policies'
    | '/_console/'
    | '/_console/disputes/$caseId'
    | '/_console/disputes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsoleRoute: typeof ConsoleRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/': {
      id: '/_console/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/about': {
      id: '/_console/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ConsoleAboutRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/disputes': {
      id: '/_console/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof ConsoleDisputesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/evaluation': {
      id: '/_console/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof ConsoleEvaluationRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/policies': {
      id: '/_console/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof ConsolePoliciesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/disputes/': {
      id: '/_console/disputes/'
      path: '/'
      fullPath: '/disputes/'
      preLoaderRoute: typeof ConsoleDisputesIndexRouteImport
      parentRoute: typeof ConsoleDisputesRoute
    }
    '/_console/disputes/$caseId': {
      id: '/_console/disputes/$caseId'
      path: '/$caseId'
      fullPath: '/disputes/$caseId'
      preLoaderRoute: typeof ConsoleDisputesCaseIdRouteImport
      parentRoute: typeof ConsoleDisputesRoute
    }
  }
}

interface ConsoleDisputesRouteChildren {
  ConsoleDisputesCaseIdRoute: typeof ConsoleDisputesCaseIdRoute
  ConsoleDisputesIndexRoute: typeof ConsoleDisputesIndexRoute
}

const ConsoleDisputesRouteChildren: ConsoleDisputesRouteChildren = {
  ConsoleDisputesCaseIdRoute: ConsoleDisputesCaseIdRoute,
  ConsoleDisputesIndexRoute: ConsoleDisputesIndexRoute,
}

const ConsoleDisputesRouteWithChildren = ConsoleDisputesRoute._addFileChildren(
  ConsoleDisputesRouteChildren,
)

interface ConsoleRouteChildren {
  ConsoleAboutRoute: typeof ConsoleAboutRoute
  ConsoleDisputesRoute: typeof ConsoleDisputesRouteWithChildren
  ConsoleEvaluationRoute: typeof ConsoleEvaluationRoute
  ConsolePoliciesRoute: typeof ConsolePoliciesRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAboutRoute: ConsoleAboutRoute,
  ConsoleDisputesRoute: ConsoleDisputesRouteWithChildren,
  ConsoleEvaluationRoute: ConsoleEvaluationRoute,
  ConsolePoliciesRoute: ConsolePoliciesRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConsoleRoute: ConsoleRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
